### PR TITLE
removed erronously added files, and fixed cmake

### PR DESCRIPTION
**Pull request by makeclean**
Removed some files which I think were added by mistake, and fixed the cmakefile

### CODE REVIEW

**Comment by pshriwise** [comment]
Are you sure you wanted to remove those .cpp files?

**Comment by makeclean** [comment]
Nope, i wanted to remove the comitted executables

**Comment by pshriwise** [comment]
🤔 I'm not seeing any committed binaries in the `main` branch...

**Comment by makeclean** [comment]
Oh, in that case, the problem was the symptom of an in place build. Before this pr, in that modifiec cmake file, the c++ files were missing their exension, cmake was finding the compiled excecutables and trying to figure out wtf they were
________________________________

**Comment by pshriwise** [comment]
Ah, I see. Yeah that would be a problem. We definitely want to include those extensions. Especially since some versions of CMake don't support automatic discovery based on the project language. Thanks for correcting that!

**Comment by pshriwise** [comment]
Once those source files are re-added (maybe by amending the current commit) I think this is ready to go!

**Review by pshriwise — APPROVED** [review]
Looks good! Thanks @makeclean!

**Pull request merged**
