### PR TITLE
Adding find_volume method for compatibility with the DAGMC interface

### PR DESCRIPTION
**Pull request by pshriwise**

### CODE REVIEW

**Comment by pshriwise** [comment]
Okay @ebknudsen. I think this should do the trick. Would you mind looking it over too and suggesting any improvements you might see?

**Comment by ebknudsen** [comment]
roger that - checking...

**Comment by ebknudsen** [comment]
Looks good to me - and it seems to work as well. One could argue that this kind of bypasses the idea of exposing the MOAB function, but I like the PR. Will merge

**Comment by pshriwise** [comment]
Totally fair point. A better long-term fix would be to build a single tree in double down as well. Someday.

**Comment by ebknudsen** [comment]
Yup someday... amen to that. We (mostly you perhaps :-) ) should do a release/tag of double_down I think.

**Pull request merged**
