### PR TITLE
removed fortran from testing scripts

### PR DESCRIPTION
**Pull request by Shimwell**
As discussing in #9 this is an update to the testing scripts which removes fortran dependency

I am sure I will need to add some additional parts here but I'm keen to see what errors are raised with this initial attempt

### CODE REVIEW

**Comment by Shimwell** [comment]
ah I forgot, github actions don't run from a PR that comes from a fork

**Comment by pshriwise** [comment]
It should run now that #11 has been merged if you rebase onto the main branch, yes?

**Comment by Shimwell** [comment]
Not rebased quite yet, looks like you have been busy.

but I got it to trigger the github action on my fork https://github.com/Shimwell/double-down/runs/1866574824?check_suite_focus=true

**Review by pshriwise — APPROVED** [review]

**Comment by pshriwise** [comment]
Works for me! Thanks @Shimwell

**Pull request merged**
