### PR TITLE
Faster find_volume with global scene

### PR DESCRIPTION
**Pull request by pshriwise**
This implements `find_volume` in a faster way. Needed to add a new `RayFireType` that keeps the triangle normals from being adjusted according to the surface sense in the triangle intersector to do so.

### CODE REVIEW

**Comment by ebknudsen** [comment]
One thing I don't understand in the find_volume function. If the point to be checked happens to be outside all volumes on an intersection trajectory with volume j, then would that not lead to a return of volume j, even though the point is outside?
From the logic of lines 759-770 I mean. Or maybe I've misunderstood something (likely)

**Comment by pshriwise** [comment]
> One thing I don't understand in the find_volume function. If the point to be checked happens to be outside all volumes on an intersection trajectory with volume j, then would that not lead to a return of volume j, even though the point is outside?
> From the logic of lines 759-770 I mean. Or maybe I've misunderstood something (likely)

This point would be considered to be in the implicit complement, which may or may not be valid depending on the use-case of the DAGMC model. This is definitely something I'd like to discuss in the DAGMC meeting tomorrow morning.

**Comment by ebknudsen** [comment]
So the understanding is that on creation of the DAGMCUniverse (to speak
OpenMC-lingo), the implicit complement is created as the complement to all
other things. Once that is done any point within the universe will alway be
inside something, and so the logic is sound. I think.

**Comment by pshriwise** [comment]
@ebknudsen I'm going to try to get a new release out soon. When you have a chance, can you let me know if there are any outstanding issues you'd like me to take a look at here?

**Comment by ebknudsen** [comment]
@pshriwise - I don't have any outstanding issues right now. So I think you can go ahead and trigger the build scripts so to speak.

**Comment by pshriwise** [comment]
> @pshriwise - I don't have any outstanding issues right now. So I think you can go ahead and trigger the build scripts so to speak.

Awesome. Thanks!

**Pull request merged**
